# Generated by Django 3.1.1 on 2021-10-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='MailId',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
