# Generated by Django 3.1.1 on 2021-10-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_formdata_symptoms'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='formdata',
            managers=[
            ],
        ),
    ]
