# Generated by Django 3.1.7 on 2022-01-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_formdata_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raag', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('music', models.CharField(max_length=100)),
            ],
        ),
    ]
