# Generated by Django 3.1.1 on 2022-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0014_recommendation_music_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='music_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
