# Generated by Django 2.2 on 2022-01-26 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0015_auto_20220123_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 20, 16, 55, 404790)),
        ),
    ]
