# Generated by Django 2.2 on 2022-01-29 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0016_recommendation_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 19, 48, 51, 804078)),
        ),
    ]
